my_app/product/models.py
PRODUCTS = {
    'iphone': {
        'name': 'iPhone 5S',
        'category': 'Phones',
        'price': 699,
    },
    'galaxy': {
        'name': 'Samsung Galaxy 5',
        'category': 'Phones',
        'price': 649,
    },
    'ipad-air': {
        'name': 'iPad Air',
        'category': 'Tablets',
        'price': 649,
    },
    'ipad-mini': {
        'name': 'iPad Mini',
        'category': 'Tablets',
        'price': 549
    }
}

my_app/catalog/views.py
import json
import os.path
from functools import wraps

from flask import Blueprint, jsonify, request, render_template, flash, redirect, url_for, abort
from flask.views import MethodView
from flask_restful import Resource
from sqlalchemy.orm import join
from werkzeug.utils import secure_filename

from my_app import db, app, ALLOWED_EXTENSIONS
from my_app.catalog.models import Product, Category, ProductForm, CategoryForm

catalog = Blueprint('catalog', __name__)


class ProductView(MethodView):
    def get(self, id=None, page=1):
        if not id:
            products = Product.query.paginate(page=page, per_page=10).items
        else:
            products = [Product.query.get(id)]
        if not products:
            abort(404)
        res = {}
        for product in products:
            res[product.id] = {
                'name': product.name,
                'price': product.price,
                'category': product.category.name,
            }
        return json.dumps(res)

    def post(self):
        pass

    def put(self):
        pass

    def delete(self):
        pass


def allowed_file(filename):
    return '.' in filename and filename.lower().rsplit('.', 1)[1] in ALLOWED_EXTENSIONS


def template_or_json(template=None):
    def decorated(f):
        @wraps(f)
        def decorated_fn(*args, **kwargs):
            ctx = f(*args, **kwargs)
            if request.headers.get("X-Requested-With") == "XMLHttpRequest" or not template:
                return jsonify(ctx)
            else:
                return render_template(template, **ctx)

        return decorated_fn

    return decorated


@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@catalog.route('/')
@catalog.route('/home')
@template_or_json('home.html')
def home():
    products = Product.query.all()
    return {'ilość': len(products)}


@catalog.route('/catalog')
@catalog.route('/catalog/<int:page>')
def products(page=1):
    products = Product.query.paginate(page=page, per_page=10)
    return render_template('products.html', products=products)


@catalog.route('/category/<id>')
def category(id):
    category = Category.query.get_or_404(id)
    return render_template('category.html', category=category)


@catalog.route('/product-create', methods=['GET', 'POST'])
def create_product():
    form = ProductForm(meta={'csrf': True})
    if form.validate_on_submit():
        name = form.name.data
        price = form.price.data
        category = Category.query.get_or_404(form.category.data)
        image = form.image.data
        if allowed_file(image.filename):
            filename = secure_filename(image.filename)
            image.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
        product = Product(name, price, category, filename)
        db.session.add(product)
        db.session.commit()
        flash('Produkt %s został dodany' % name, 'success')
        return redirect(
            url_for('catalog.product', id=product.id))
    if form.errors:
        flash(form.errors, 'danger')
    return render_template('product-create.html', form=form)


@catalog.route('/category-create', methods=['GET', 'POST'])
def create_category():
    form = CategoryForm(meta={'csrf': False})
    if form.validate_on_submit():
        name = form.name.data
        category = Category(name)
        db.session.add(category)
        db.session.commit()
        flash('Kategoria %s została dodana' % name, 'success')
        return redirect(
            url_for('catalog.product', id=category.id))
    if form.errors:
        flash(form.errors, 'danger')
    return render_template('category-create.html', form=form)


@catalog.route('/product/<id>')
def product(id):
    product = Product.query.get_or_404(id)
    return render_template('product.html', product=product)


@catalog.route('/categories')
def categories():
    categories = Category.query.all()
    return render_template('categories.html', categories=categories)


@catalog.route('/product-search')
@catalog.route('/product-search/<int:page>')
def product_search(page=1):
    name = request.args.get('name')
    price = request.args.get('price')
    company = request.args.get('company')
    category = request.args.get('category')
    products = Product.query
    if name:
        products = products.filter(Product.name.like('%' + name + '%'))
    if price:
        products = products.filter(Product.price == price)
    if company:
        products = products.filter(Product.company.like('%' + company + '%'))
    if category:
        products = products.select_from(join(Product, Category)).filter(Category.name.like('%' + category + '%'))

    return render_template('products.html', products=products.paginate(page, 10))


@catalog.route('/req', methods=['GET', 'POST'])
def some_req():
    if request.method == 'GET':
        bar = request.args.get('foo', 'bar')
    else:
        bar = request.form.get('foo', 'bar')
    return 'Simple request where foo is %s' % bar


@catalog.route('/test/<string(minlength=2, maxlength=3):code>')
def get_name(code):
    return code


@catalog.route('/test2/<int(min=18,max=99):age>')
def get_age(age):
    return str(age)


class ProductApi(Resource):
    def get(self, id=None):
        return 'To jest get z api'

    def post(self):
        pass

    def put(self, id):
        pass

    def delete(self, id):
        pass

my_app/product/views.py
from flask import Blueprint, render_template, request
from werkzeug.exceptions import abort

from my_app.product.models import PRODUCTS

product_blueprint = Blueprint('product', __name__)


@product_blueprint.route('/')
@product_blueprint.route('/home')
def home():
    return render_template('home.html', products=PRODUCTS)


@product_blueprint.route('/product/<key>')
def product(key):
    prod = PRODUCTS.get(key)
    if not prod:
        abort(404)
    return render_template('product.html', product=prod)


@product_blueprint.context_processor
def some_processor():
    def full_name(product):
        return '{0} / {1}'.format(product['category'], product['name'])

    return {'full_name': full_name}


@product_blueprint.app_template_filter('full_name')
def full_name_filter(product):
    return '{0} / {1}'.format(product['category'], product['name'])

my_app/templates/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Flask app v.2</title>
    <link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/main.css') }}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-dark bg-dark fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('catalog.home') }}">Katalog produktów</a>
        </div>
    </div>
</nav>
<br/>
<div>
    {% for category, message in get_flashed_messages(with_categories=true) %}
    <div class="alert alert-{{category}} alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
</div>
<div class="container">
    {% block container %}{% endblock %}
</div>
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
</body>
</html>

my_app/templates/categories.html
{% extends 'home.html' %}
{% block container %}
<div class="top-pad">
{% for category in categories %}
    <a href="{{ url_for('catalog.category', id=category.id) }}">
        <h2>{{ category.name }}</h2>
    </a>
    {% endfor %}
</div>
{% endblock %}

my_app/templates/category-create.html
{% extends 'home.html' %}
{% block container %}
<div class="top-pad">
<form method="post" action="{{ url_for('catalog.create_category') }}"
      role="form">
    <div class="form-group">
        {{ form.name.label }}: {{ form.name() }}
    </div>
    <button type="submit" class="btn btn-default">SUBMIT</button>
</form>
</div>
{% endblock %}

my_app/templates/category.html
{% extends 'home.html' %}
{% block container %}
<div class="top-pad">
    <h2>{{ category.name }}</h2>
    <div class="well">
{% for product in category.products %}
    <a href="{{ url_for('catalog.product', id=product.id) }}">
        <h2>{{ product.name }}</h2>
    </a>
    {% endfor %}
    </div>
</div>
{% endblock %}

my_app/templates/home.html
{% extends 'base.html' %}

{% block container %}
<div class="top-pad">
    <div class="top-pad offset-1 col-sm-10">
        <div class="card text-center">
            <div class="card-body">
                <h3>
                    <a href="{{ url_for('catalog.products') }}">Kliknij tutaj!</a>
                </h3>
            </div>
        </div>
    </div>
</div>
{% endblock %}

my_app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Title</title>
    <link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/main.css') }}" rel="stylesheet">
</head>
<body>
 <p>Zawartość listy:</p>
 <hr>
 <p><b>{{ mess }}</b></p>
</body>
</html>

my_app/templates/product-create.html
{% extends 'home.html' %}
{% block container %}
<div class="top-pad">
<form method="post" action="{{ url_for('catalog.create_product') }}"
      role="form" enctype="multipart/form-data">
    {{ form.csrf_token }}
    <div class="form-group">
        {{ form.name.label }}: {{ form.name() }}
    </div>
    <div class="form-group">
       {{ form.price.label }}: {{ form.price() }}
    </div>
    <div class="form-group">
        {{ form.category.label }}: {{ form.category() }}
    </div>
    <div class="form-group">
        {{ form.image.label }}: {{ form.image(style='display:inline;') }}
    </div>
    <button type="submit" class="btn btn-default">SUBMIT</button>
</form>
</div>
{% endblock %}

my_app/templates/product.html
{% extends 'home.html' %}
{% block container %}
<div class="top-pad">
    <h1>{{ product.name }}</h1>
    <h3><small>{{ product.category.name }}</small></h3>
    <h5>{{ product.price }}</h5>
    <h4>{{ product.company }}</h4>
    <img src="{{ url_for('static', filename='images/' + product.image_path) }}"/>
</div>
{% endblock %}

my_app/templates/products.html
{% extends 'home.html' %}
{% block container %}
<div class="top-pad">
{% for product in products.items %}
    <div class="well">
        <h2>
            <a href="{{ url_for('catalog.product', id=product.id) }}">{{ product.name }}</a>
            <small> PLN {{ product.price }}</small>
        </h2>
    </div>
{% endfor %}
    {% if products.has_prev %}
    <a href="{{ url_for(request.endopoint, page=products.prev_num) }}">{{" << Poprzednia strona" }}</a>
{% endif %}
{% if products.has_next %}
    <a href="{{ url_for(request.endopoint, page=products.next_num) }}">{{" Następna strona >>" }}</a>
{% endif %}
</div>
{% endblock %}